---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
components:
  - ../../components/common
resources:
  #- ./deluge/ks.yaml
  - ./audiobookshelf/ks.yaml
  - ./discoverylastfm/ks.yaml
  - ./lidarr-pr/ks.yaml
  #- ./jellyfin/ks.yaml
  - ./overseerr/ks.yaml
  - ./plex/ks.yaml
  - ./prowlarr/ks.yaml
  - ./pv-smb.yaml
  - ./radarr/ks.yaml
  - ./readarr/ks.yaml
  - ./readarr-audio/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./secrets.sops.yaml
  - ./sonarr/ks.yaml
  - ./slskd/ks.yaml
  - ./tautulli/ks.yaml
