apiVersion: v1
kind: Secret
metadata:
    name: openwebui-secrets
    namespace: cloud
stringData:
    OAUTH_PROVIDER_NAME: ENC[AES256_GCM,data:sCqCHlie4smb,iv:RF9+XCXJI2eWEy5FpBzIR8ZWLtoY/1D8RzyjQP+CFD4=,tag:2C0nBGe+D6TFP7k5oNbPSg==,type:str]
    OPENID_PROVIDER_URL: ENC[AES256_GCM,data:Qihkn/55PUiZONkebr1MhCqUH0Bc/X+GyH0ni+xPpJ0Rebc3AQlUsm33zxEmTmZ/nIOTl0aofWHMAwlhYQtGo62jzYnsnoTBPYfosSws,iv:Hr3Aq39YFmhh+FM4qQxRIQ9LvhrWZTsyUe1R9zPMkEg=,tag:bQgnu72fzdpa2NQpfGFMvA==,type:str]
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:8QeBsXzIHIHQkGP0qFk3pcUVuPfEGX7a7CwQBDU8vC3m4WeFzQQ4EA==,iv:3c8lomx92+zgf1lJBaKZYZgUFeCZqmYv0mLI0m02gto=,tag:cQD3LC/8b18HVeX1srccRA==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:Jp36SKlilLLSk8MeEMOsJrF2yo3XTgsJ4YlgzHSSCeQJfh5QB316Ln+JQduHQQBns4yd4qEENJwed90HnhP7EoN2L7Gur34eU3MtL6tMsQT1HZ6Ac+aXOKhMtYekxLD8ga8Fbz7peH+5GS+IWJenuiRBXE1inmAXYeCnL6Zh4AA=,iv:D7Txmin91dS7a9azobmYndqjXZTV3vhsZ+0oMNHXXWE=,tag:DzKvfA/YWrFWdPICsPYhqg==,type:str]
    OAUTH_SCOPES: ENC[AES256_GCM,data:cpAqE0xbPJQTe6VzaMP5miaIC/8=,iv:JfnIbVnliHTyQX3gb6Jshq5bhLq7vPd0sRyoq2m62G8=,tag:nlBcdHAmJvxJAWAFO3bRrA==,type:str]
    OPENID_REDIRECT_URI: ENC[AES256_GCM,data:ZXdFaS6WXk/xviYyAajRQfppSeYq83dXN2BLZD700UwUbpBLYiD3,iv:LQHJtylfjhmrBXvlhkN0DgVC07Kg/TpTW8/y02JUplU=,tag:HbO1w9pxEP6rHccWW//Mdw==,type:str]
sops:
    age:
        - recipient: age1e8t93m32pkq6v5pgce4gm39xmtm967j9scmnvnrwpkaccwvunsyspwz3kp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBV1J2c3JOdU9mUUpmemI2
            UWRrY3FvZllCQ0h0WGVJaTFUaEIvanE1djJZClJLa3RzYXFNMnBSOTMwRGxpbDEx
            YzdxRGJDNFpQaGova0VZcG9zdHV0MUkKLS0tIG80R1U0NUJ0ZlZ4UGJhU2dLVEJ4
            N0JHamJsSlZzNHVFSnNZbTlmd0RjdmcKB765mHQ+sd19oRHVSEJyBlNWGnfEMahc
            w1RgTvejuSlQEFDCRZiRLfwJ+UrTwNOUlvPbIUA83S98rwKO139a4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-12T21:16:55Z"
    mac: ENC[AES256_GCM,data:qNGiz5DPpg9TwuT1PhVjswbU/dwwOglMBlCEEMYyCGY1SjZ4Z3BmTcAFgphvF0uFPp2Ghl6mOIMO89EA3hTuRoxCpqKs4wQnZTr4+X7dXR8NQz/j5l4xjNYq8dQUF4obSOVrEclKXjbX1sBxYXWFUMv7yA+0arArmfEAYmfANDc=,iv:G/X3QXRKotak0uYX9QrNRZIk4hL9vlXp7Sfjq9Pnq5I=,tag:3wnJ89mEGAwz4LuO7NezHg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
