apiVersion: v1
kind: Secret
metadata:
    name: openwebui-secrets
    namespace: ai
stringData:
    OAUTH_PROVIDER_NAME: ENC[AES256_GCM,data:sxQF6aq4e2vO,iv:Ztmv3doayctxyM3LLJ6P41/Jzk2MtYpP4cTTBt1Utas=,tag:fVtAeBY5cYYc3r+HvdtOuA==,type:str]
    OPENID_PROVIDER_URL: ENC[AES256_GCM,data:gEObXl95A8gk+PHgxj7LXzz2IoLCndCF82Wevkcal3C1F6NAhvGjq2QNETAb5hO6DH4J4A==,iv:oJ6Dmtpbk/J08CbRiFX92YgcLX2Y9EHc8StkEsl/F8o=,tag:NGePAunU1C2wyUuAb1Gd6A==,type:str]
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:Ye0iNKJq75rMA+TgHXiqP7fHMsr4CXwXQqWe4kh2+K8egVSAEzq1Lg==,iv:1ICU9QCionCSKGGs17Kzw1n+UjUwjYfyPRIKypCq9cw=,tag:DNrsBNzN8H+uUiiLeELQvw==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:s6z+KgHuZUBRGYmRZeSeomSvqzJU96ggIzh9knHolQ/Chu/YoipkFbIHgfxx/bsoPixtLojvNMm3rQKry9qHg4C4nBurh0a7gUP1rB/kmYSTreidrahkPbKf6LUIXuWPFTRt6WsGx6EW67jtgIcDbrR7StuGsCkfvvgEIwe/99Y=,iv:JMgIhU+2gykYpXdjtu9aNNqPBpRsDApENcaPOWCSg9U=,tag:5d2NeNTxstDipMbaxLIioA==,type:str]
    OAUTH_SCOPES: ENC[AES256_GCM,data:cpAqE0xbPJQTe6VzaMP5miaIC/8=,iv:JfnIbVnliHTyQX3gb6Jshq5bhLq7vPd0sRyoq2m62G8=,tag:nlBcdHAmJvxJAWAFO3bRrA==,type:str]
    OPENID_REDIRECT_URI: ENC[AES256_GCM,data:ZXdFaS6WXk/xviYyAajRQfppSeYq83dXN2BLZD700UwUbpBLYiD3,iv:LQHJtylfjhmrBXvlhkN0DgVC07Kg/TpTW8/y02JUplU=,tag:HbO1w9pxEP6rHccWW//Mdw==,type:str]
    OAUTH_MERGE_ACCOUNTS_BY_EMAIL: ENC[AES256_GCM,data:7mIeZA==,iv:4V63Ez2TK/MkCWMmp6Zr/T87qqr4TUCu7HlWCwHxSMY=,tag:buqIH3AYxRqhpflfyHJwgQ==,type:bool]
sops:
    age:
        - recipient: age1e8t93m32pkq6v5pgce4gm39xmtm967j9scmnvnrwpkaccwvunsyspwz3kp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBV1J2c3JOdU9mUUpmemI2
            UWRrY3FvZllCQ0h0WGVJaTFUaEIvanE1djJZClJLa3RzYXFNMnBSOTMwRGxpbDEx
            YzdxRGJDNFpQaGova0VZcG9zdHV0MUkKLS0tIG80R1U0NUJ0ZlZ4UGJhU2dLVEJ4
            N0JHamJsSlZzNHVFSnNZbTlmd0RjdmcKB765mHQ+sd19oRHVSEJyBlNWGnfEMahc
            w1RgTvejuSlQEFDCRZiRLfwJ+UrTwNOUlvPbIUA83S98rwKO139a4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-13T12:02:05Z"
    mac: ENC[AES256_GCM,data:eoHkVTrcg1heFWG/7xVTJ+tWz4zHbKWyVUYYYsHzLUpvJydekVEU44uG7/ZRgq/SLIE6hrx5RcQreDrbDOgPAgPr/1S8DNtALtNeGhBPecvlRbYC5zITSPxVWGk/OuPkPEy+TuYolOjnUOWk7DHtGRZEIRNO4COfwj01osE0Rlk=,iv:jNnPWs2SbsiqRwfwA3MyeFk+HEgxfWzAvkWk77ZnqhY=,tag:103tolr3PgnVb3N5FX7uxQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
