apiVersion: v1
kind: Secret
metadata:
    name: openwebui-secrets
    namespace: cloud
stringData:
    OAUTH_PROVIDER_NAME: ENC[AES256_GCM,data:VHHDoY38PSeM,iv:dzWeVbg5OoNwXf5u3XlQ7HFd8SbD5kBnJ+or1xXTQhQ=,tag:i1coZMRZ8/LywvmgEDc2eA==,type:str]
    OPENID_PROVIDER_URL: ENC[AES256_GCM,data:5Vjiu20D4QYiZ3Pipo4Kubq/manIR74Y5l2URZ+rkaFtmvbs8rQAu+6Yl/wBcYLMEW2cFA==,iv:2GN3Q9buvxRNKPPRmyH+77azwW1b8XLjZqMdOSs61nM=,tag:fyKMYyxsKOu2WDWdqH67RQ==,type:str]
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:Ye0iNKJq75rMA+TgHXiqP7fHMsr4CXwXQqWe4kh2+K8egVSAEzq1Lg==,iv:1ICU9QCionCSKGGs17Kzw1n+UjUwjYfyPRIKypCq9cw=,tag:DNrsBNzN8H+uUiiLeELQvw==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:s6z+KgHuZUBRGYmRZeSeomSvqzJU96ggIzh9knHolQ/Chu/YoipkFbIHgfxx/bsoPixtLojvNMm3rQKry9qHg4C4nBurh0a7gUP1rB/kmYSTreidrahkPbKf6LUIXuWPFTRt6WsGx6EW67jtgIcDbrR7StuGsCkfvvgEIwe/99Y=,iv:JMgIhU+2gykYpXdjtu9aNNqPBpRsDApENcaPOWCSg9U=,tag:5d2NeNTxstDipMbaxLIioA==,type:str]
    OAUTH_SCOPES: ENC[AES256_GCM,data:cpAqE0xbPJQTe6VzaMP5miaIC/8=,iv:JfnIbVnliHTyQX3gb6Jshq5bhLq7vPd0sRyoq2m62G8=,tag:nlBcdHAmJvxJAWAFO3bRrA==,type:str]
    OPENID_REDIRECT_URI: ENC[AES256_GCM,data:ZXdFaS6WXk/xviYyAajRQfppSeYq83dXN2BLZD700UwUbpBLYiD3,iv:LQHJtylfjhmrBXvlhkN0DgVC07Kg/TpTW8/y02JUplU=,tag:HbO1w9pxEP6rHccWW//Mdw==,type:str]
sops:
    age:
        - recipient: age1e8t93m32pkq6v5pgce4gm39xmtm967j9scmnvnrwpkaccwvunsyspwz3kp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBV1J2c3JOdU9mUUpmemI2
            UWRrY3FvZllCQ0h0WGVJaTFUaEIvanE1djJZClJLa3RzYXFNMnBSOTMwRGxpbDEx
            YzdxRGJDNFpQaGova0VZcG9zdHV0MUkKLS0tIG80R1U0NUJ0ZlZ4UGJhU2dLVEJ4
            N0JHamJsSlZzNHVFSnNZbTlmd0RjdmcKB765mHQ+sd19oRHVSEJyBlNWGnfEMahc
            w1RgTvejuSlQEFDCRZiRLfwJ+UrTwNOUlvPbIUA83S98rwKO139a4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-13T11:41:07Z"
    mac: ENC[AES256_GCM,data:RwEvJ+8YGpgukCe9Aiw3gULrj3ibWXYzx1qdm9nRtBn4i2zW3zSM6FMBYk8f8SZeo1i1frQb49x3u7eYrGnspgPqlPXmAGFFm/Ilb/POmIOeeMX/o0Xmsrrtx9sYq6PTsuGY24DWoQmgsDqqcVxhemc+MClZJS+i7218HlAV6SY=,iv:axzWHB2XWp7Rm74JvPv9m7OOjq1Vw84JV+0YXModsOI=,tag:KIHgI2KRR4GRaD/UQr0FLA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
