apiVersion: v1
kind: Secret
metadata:
    name: openwebui-secrets
    namespace: cloud
stringData:
    OAUTH_PROVIDER_NAME: ENC[AES256_GCM,data:bfc3TkCGEA31,iv:ZSn33pGXEcaIr3Y98KGRl+P3Au5obNEYtOScJeTuH7M=,tag:G0uT2NOr7j12rjaGuqBDkA==,type:str]
    OPENID_PROVIDER_URL: ENC[AES256_GCM,data:5hl/ZLulivuoNZC6XlgrF8wZik3SyBroypgpmbXatGgBH5VurzEXQ4LMEjswWSTzwtz1dQ==,iv:g+lNV4q+OyySoqKnooTiPHH+ooyZXjomkjLTxxNHfJE=,tag:TVawIBNpECJ1CuIBseT16A==,type:str]
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:eA06kHwL7LXOo9yOKiZWXRqRkKUMapy38DZWRirtfwpQQujFayJZyg==,iv:BkdA3w4wUzo0Q6ZhtnYTSGikq1oBn/Mt3LuOjdHd4ns=,tag:c+fXtmbqOq/8qthQeR4Gpg==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:fZIQn7WfeiW+1oIa8d3J/3UmlzPB8ewa5CLpa7LFn7o=,iv:5Djf+EzWvGQKNOB6A9sDAwGSEWJOdlfPC1GSda9tTLA=,tag:EJjJFnGVGh0re+scOkPZ3A==,type:str]
    OAUTH_SCOPES: ENC[AES256_GCM,data:cpAqE0xbPJQTe6VzaMP5miaIC/8=,iv:JfnIbVnliHTyQX3gb6Jshq5bhLq7vPd0sRyoq2m62G8=,tag:nlBcdHAmJvxJAWAFO3bRrA==,type:str]
    OPENID_REDIRECT_URI: ENC[AES256_GCM,data:ZXdFaS6WXk/xviYyAajRQfppSeYq83dXN2BLZD700UwUbpBLYiD3,iv:LQHJtylfjhmrBXvlhkN0DgVC07Kg/TpTW8/y02JUplU=,tag:HbO1w9pxEP6rHccWW//Mdw==,type:str]
sops:
    age:
        - recipient: age1e8t93m32pkq6v5pgce4gm39xmtm967j9scmnvnrwpkaccwvunsyspwz3kp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBV1J2c3JOdU9mUUpmemI2
            UWRrY3FvZllCQ0h0WGVJaTFUaEIvanE1djJZClJLa3RzYXFNMnBSOTMwRGxpbDEx
            YzdxRGJDNFpQaGova0VZcG9zdHV0MUkKLS0tIG80R1U0NUJ0ZlZ4UGJhU2dLVEJ4
            N0JHamJsSlZzNHVFSnNZbTlmd0RjdmcKB765mHQ+sd19oRHVSEJyBlNWGnfEMahc
            w1RgTvejuSlQEFDCRZiRLfwJ+UrTwNOUlvPbIUA83S98rwKO139a4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-12T12:04:10Z"
    mac: ENC[AES256_GCM,data:P8inh5sfruglf7Xdw57JetUCNT3VbY3P7Ecm4PmV+fAS343wWd3MlIpD/XTZAkfIx2vIGEsfaTh6yfz2NHiw3rSZ7WkQJyg2jv1glHIGAzOcz2tRlzciGHubsB9atWmpd0dAMMURjA8MERYzYN2X/vmsxHkAD6XsFD5Qp6DNGCU=,iv:QOEVYEUxh3pumLdioFwPOfwhcidEj0Np0GevsEG/jwY=,tag:2X8qvYMZ+4NAvXxv0ATfWw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
