apiVersion: v1
kind: Secret
metadata:
    name: openwebui-secrets
    namespace: ai
stringData:
    OAUTH_PROVIDER_NAME: ENC[AES256_GCM,data:J7IqDHqmRAHV,iv:Vy+DD0LXdl/6k0aJ5/FiVs13gQN4MoMpj0vV8RdmnpQ=,tag:FEHhNshE5MW3fZtdvoh8qA==,type:str]
    OPENID_PROVIDER_URL: ENC[AES256_GCM,data:Yp/q0AxsHCCw/knoxVYnU16QEHCkYc6ON8JTBbdxz+M1qG3dZ9BfQhqPcrhMnNqWFirf+PaataBbjaUhsyXQbhFJ,iv:ivBIiCnBZFWfZSvkcamMVIezObB0CPSSE3zx1hCwF00=,tag:VI4PnzPHxfvIMzh1FE6JdQ==,type:str]
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:Ye0iNKJq75rMA+TgHXiqP7fHMsr4CXwXQqWe4kh2+K8egVSAEzq1Lg==,iv:1ICU9QCionCSKGGs17Kzw1n+UjUwjYfyPRIKypCq9cw=,tag:DNrsBNzN8H+uUiiLeELQvw==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:s6z+KgHuZUBRGYmRZeSeomSvqzJU96ggIzh9knHolQ/Chu/YoipkFbIHgfxx/bsoPixtLojvNMm3rQKry9qHg4C4nBurh0a7gUP1rB/kmYSTreidrahkPbKf6LUIXuWPFTRt6WsGx6EW67jtgIcDbrR7StuGsCkfvvgEIwe/99Y=,iv:JMgIhU+2gykYpXdjtu9aNNqPBpRsDApENcaPOWCSg9U=,tag:5d2NeNTxstDipMbaxLIioA==,type:str]
    OAUTH_SCOPES: ENC[AES256_GCM,data:cpAqE0xbPJQTe6VzaMP5miaIC/8=,iv:JfnIbVnliHTyQX3gb6Jshq5bhLq7vPd0sRyoq2m62G8=,tag:nlBcdHAmJvxJAWAFO3bRrA==,type:str]
    OPENID_REDIRECT_URI: ENC[AES256_GCM,data:ZXdFaS6WXk/xviYyAajRQfppSeYq83dXN2BLZD700UwUbpBLYiD3,iv:LQHJtylfjhmrBXvlhkN0DgVC07Kg/TpTW8/y02JUplU=,tag:HbO1w9pxEP6rHccWW//Mdw==,type:str]
sops:
    age:
        - recipient: age1e8t93m32pkq6v5pgce4gm39xmtm967j9scmnvnrwpkaccwvunsyspwz3kp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBV1J2c3JOdU9mUUpmemI2
            UWRrY3FvZllCQ0h0WGVJaTFUaEIvanE1djJZClJLa3RzYXFNMnBSOTMwRGxpbDEx
            YzdxRGJDNFpQaGova0VZcG9zdHV0MUkKLS0tIG80R1U0NUJ0ZlZ4UGJhU2dLVEJ4
            N0JHamJsSlZzNHVFSnNZbTlmd0RjdmcKB765mHQ+sd19oRHVSEJyBlNWGnfEMahc
            w1RgTvejuSlQEFDCRZiRLfwJ+UrTwNOUlvPbIUA83S98rwKO139a4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T21:32:57Z"
    mac: ENC[AES256_GCM,data:N27zko1plWf1njgPPm5slzVYNEAWUBsNovKImEYz9kqaX5SlXtcYmX4ZrVAVjJJo8xTC4HA+Jzq4TgZ7I82ztHyvBb+hm1/y/3eDoeR891VgkZtmku790/vwBGyDEOcimpjgRL40uickXrsE297ssMN+SrgZgx3L8Y2SUmHzvnM=,iv:pMrlw1CBvkfjxhajbpHsaGlnw5dZiGyP2Z041Y4inDc=,tag:FDuRdJUjzhgLC6dDCyxKVw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
