---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app initiative
  namespace: &namespace dev
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  path: ./kubernetes/apps/dev/initiative/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    - name: csi-driver-cephfs
      namespace: storage
    - name: crunchy-postgres-operator
      namespace: database
  components:
  - ../../../../components/gatus/external
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
      - kind: ConfigMap
        name: cluster-settings
    substitute:
      APP: *app
      NS: *namespace
      DB_NAME: *app
      DB_USER: *app
      GATUS_DOMAIN: ${SECRET_DOMAIN}
      GATUS_SUBDOMAIN: *app
      GATUS_PATH: /
      GATUS_STATUS: "200"
