---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stash-config
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: csi-cephfs-sc
  volumeName: stash-config-pv

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: stash-config-pv
spec:
  storageClassName: csi-cephfs-sc
  claimRef:
    name: stash-config
    namespace: cloud
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: cephfs.csi.ceph.com
    nodeStageSecretRef:
      # node stage secret name
      name: csi-cephfs-secret
      # node stage secret namespace where above secret is created
      namespace: storage
    volumeAttributes:
      # Required options from storageclass parameters need to be added in volumeAttributes
      "clusterID": "ace7b6a4-115a-42f7-ba4f-32ceeb11e3c3"
      "fsName": "k8s-cephfs"
      "staticVolume": "true"
      "rootPath": /volumes/csi/k8s-cloud/stash/config
    # volumeHandle can be anything, need not to be same
    # as PV name or volume name. keeping same for brevity
    volumeHandle: stashconfig

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stash-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: csi-cephfs-sc
  volumeName: stash-data-pv

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: stash-data-pv
spec:
  storageClassName: csi-cephfs-sc
  claimRef:
    name: stash-data
    namespace: cloud
  capacity:
    storage: 200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: cephfs.csi.ceph.com
    nodeStageSecretRef:
      # node stage secret name
      name: csi-cephfs-secret
      # node stage secret namespace where above secret is created
      namespace: storage
    volumeAttributes:
      # Required options from storageclass parameters need to be added in volumeAttributes
      "clusterID": "ace7b6a4-115a-42f7-ba4f-32ceeb11e3c3"
      "fsName": "k8s-cephfs"
      "staticVolume": "true"
      "rootPath": /volumes/csi/k8s-cloud/stash/data
    # volumeHandle can be anything, need not to be same
    # as PV name or volume name. keeping same for brevity
    volumeHandle: stashdata

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stash-generated
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: csi-cephfs-sc
  volumeName: stash-generated-pv

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: stash-generated-pv
spec:
  storageClassName: csi-cephfs-sc
  claimRef:
    name: stash-generated
    namespace: cloud
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: cephfs.csi.ceph.com
    nodeStageSecretRef:
      # node stage secret name
      name: csi-cephfs-secret
      # node stage secret namespace where above secret is created
      namespace: storage
    volumeAttributes:
      # Required options from storageclass parameters need to be added in volumeAttributes
      "clusterID": "ace7b6a4-115a-42f7-ba4f-32ceeb11e3c3"
      "fsName": "k8s-cephfs"
      "staticVolume": "true"
      "rootPath": /volumes/csi/k8s-cloud/stash/generated
    # volumeHandle can be anything, need not to be same
    # as PV name or volume name. keeping same for brevity
    volumeHandle: stashgenerated

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stash-metadata
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: csi-cephfs-sc
  volumeName: stash-metadata-pv

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: stash-metadata-pv
spec:
  storageClassName: csi-cephfs-sc
  claimRef:
    name: stash-metadata
    namespace: cloud
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: cephfs.csi.ceph.com
    nodeStageSecretRef:
      # node stage secret name
      name: csi-cephfs-secret
      # node stage secret namespace where above secret is created
      namespace: storage
    volumeAttributes:
      # Required options from storageclass parameters need to be added in volumeAttributes
      "clusterID": "ace7b6a4-115a-42f7-ba4f-32ceeb11e3c3"
      "fsName": "k8s-cephfs"
      "staticVolume": "true"
      "rootPath": /volumes/csi/k8s-cloud/stash/metadata
    # volumeHandle can be anything, need not to be same
    # as PV name or volume name. keeping same for brevity
    volumeHandle: stashmeatdata

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stash-cache
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: csi-cephfs-sc
  volumeName: stash-cache-pv

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: stash-cache-pv
spec:
  storageClassName: csi-cephfs-sc
  claimRef:
    name: stash-cache
    namespace: cloud
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: cephfs.csi.ceph.com
    nodeStageSecretRef:
      # node stage secret name
      name: csi-cephfs-secret
      # node stage secret namespace where above secret is created
      namespace: storage
    volumeAttributes:
      # Required options from storageclass parameters need to be added in volumeAttributes
      "clusterID": "ace7b6a4-115a-42f7-ba4f-32ceeb11e3c3"
      "fsName": "k8s-cephfs"
      "staticVolume": "true"
      "rootPath": /volumes/csi/k8s-cloud/stash/cache
    # volumeHandle can be anything, need not to be same
    # as PV name or volume name. keeping same for brevity
    volumeHandle: stashcache

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stash-blobs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: csi-cephfs-sc
  volumeName: stash-blobs-pv

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: stash-blobs-pv
spec:
  storageClassName: csi-cephfs-sc
  claimRef:
    name: stash-blobs
    namespace: cloud
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: cephfs.csi.ceph.com
    nodeStageSecretRef:
      # node stage secret name
      name: csi-cephfs-secret
      # node stage secret namespace where above secret is created
      namespace: storage
    volumeAttributes:
      # Required options from storageclass parameters need to be added in volumeAttributes
      "clusterID": "ace7b6a4-115a-42f7-ba4f-32ceeb11e3c3"
      "fsName": "k8s-cephfs"
      "staticVolume": "true"
      "rootPath": /volumes/csi/k8s-cloud/stash/blobs
    # volumeHandle can be anything, need not to be same
    # as PV name or volume name. keeping same for brevity
    volumeHandle: stashblobs
