---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tautulli-config
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: csi-cephfs-sc
  volumeName: tautulli-config-pv

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tautulli-config-pv
spec:
  storageClassName: csi-cephfs-sc
  claimRef:
    name: tautulli-config
    namespace: media
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: cephfs.csi.ceph.com
    nodeStageSecretRef:
      # node stage secret name
      name: csi-cephfs-secret
      # node stage secret namespace where above secret is created
      namespace: storage
    volumeAttributes:
      # Required options from storageclass parameters need to be added in volumeAttributes
      "clusterID": "ace7b6a4-115a-42f7-ba4f-32ceeb11e3c3"
      "fsName": "k8s-cephfs"
      "staticVolume": "true"
      "rootPath": /volumes/csi/k8s-media/tautulli/config
    # volumeHandle can be anything, need not to be same
    # as PV name or volume name. keeping same for brevity
    volumeHandle: tautulli
