apiVersion: v1
kind: Secret
metadata:
    name: foundrydh-secrets
    namespace: cloud
stringData:
    FOUNDRY_USERNAME: ENC[AES256_GCM,data:dSll1cM=,iv:c53DOnjMF5NFutn7uCanromMv0liXyRzEgC6KZz9Z/E=,tag:82TZYCy9amLizsJ4OSFF8g==,type:str]
    FOUNDRY_PASSWORD: ENC[AES256_GCM,data:dHoG2GV6eAD5yC6gpf43Wg==,iv:BQLjJ8FdP4tM6c+2AnsHirsoT4TqXRySS24yxuYuCQI=,tag:6Kq1nZb4lL2KPOKDOCxnFQ==,type:str]
    FOUNDRY_ADMIN_KEY: ENC[AES256_GCM,data:WfIoy4s/dGBaocFq02XgNw==,iv:dcwuVTSdPzO72iVZDDIn4m9FRzihSU6AvijHzm9bJfM=,tag:CoMtWv6la1YisPfoGj7Fjg==,type:str]
    FOUNDRY_PASSWORD_SALT: ENC[AES256_GCM,data:ji0Ju6lAXU1i,iv:+xc2om+bruOcpncZjnznaFZMTAo3zypVz2fjcANQg9w=,tag:IEnx7K1xHcvNeD5Tm7FMeQ==,type:str]
sops:
    age:
        - recipient: age1e8t93m32pkq6v5pgce4gm39xmtm967j9scmnvnrwpkaccwvunsyspwz3kp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBV1J2c3JOdU9mUUpmemI2
            UWRrY3FvZllCQ0h0WGVJaTFUaEIvanE1djJZClJLa3RzYXFNMnBSOTMwRGxpbDEx
            YzdxRGJDNFpQaGova0VZcG9zdHV0MUkKLS0tIG80R1U0NUJ0ZlZ4UGJhU2dLVEJ4
            N0JHamJsSlZzNHVFSnNZbTlmd0RjdmcKB765mHQ+sd19oRHVSEJyBlNWGnfEMahc
            w1RgTvejuSlQEFDCRZiRLfwJ+UrTwNOUlvPbIUA83S98rwKO139a4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T13:31:57Z"
    mac: ENC[AES256_GCM,data:G9zGpB7FrTY9ZCi6y0sfrVafCWl97462+mcPhJCvvZjVX0qWfsFV9ehXfCsLyW1sbyRzOeMoBuhXS1R5lQI7yL+s/diiI9QrKKCWh2jdYzKBast8cEPhMPhPTNsNADlAN51mMy39Qw1VNo2Dhu0ZSvXeu48/fATmENZ545fEvDQ=,iv:/NAhZjXq98q58IZ+cCXvrJbyixT9pQKeMK11kgVNWz8=,tag:TG/FVpRQD6Qw0bZvGcfDHg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
