---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ${APP}-db
  namespace: dev
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: crunchy-pgo-secrets
  target:
    name: ${DB_USER}-db-secret
    template:
      engineVersion: v2
      data:
        POSTGRES_URI: '{{ index . "pgbouncer-uri" }}'
        POSTGRES_SUPER_PASS: ${SECRET_PG_PASSWORD}


  dataFrom:
    - extract:
        key: postgres-pguser-${DB_USER}
