apiVersion: v1
kind: Secret
metadata:
    name: planka-secrets
    namespace: dev
stringData:
    OIDC_ISSUER: ENC[AES256_GCM,data:xWriDGK7gRbIR4amL27fFagcMoO5JMMfwXnN+nbegWdAYpY5RiO8jQLaew==,iv:GcZw6/nlYwC/yI9ofaUOouLXZ4cd//Sr7yJjt85Wle0=,tag:X88nmPpjhAKq5ORw2Hzueg==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:G2PDigVRtgDc9uOVFjMrGBFlz3hIkyRaN9iTLdm4ZGobCSzrjgWlcg==,iv:3wrxdWpDHh7Xvn4lkgmtLB7Saq18ttjq3IU/wUlutQg=,tag:4ryVJvsIlZPG7EzdgcCpoA==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:lUMZ/qJ9eDAznxPK4eqv8csggsCrrGwOApCr8ru+CI4J2+tXg8D7g+Zk5qw8Y0ASxUvugG6b3FfKcAtnv1I/6tYJZcfKkbg/jXwkGIc/n+24bEN2F3QfRVVjZVxtewtbXaoF3tnQwip+clNUNs/WwWdvnP8DXg1jM/WV2D36GFw=,iv:2eJegzkbgmA7VY4MiXqOtSFIY3BaFqiex4QmBnqCfGI=,tag:JXfbxgY54m8EBV1rbUmrAA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8t93m32pkq6v5pgce4gm39xmtm967j9scmnvnrwpkaccwvunsyspwz3kp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBV1J2c3JOdU9mUUpmemI2
            UWRrY3FvZllCQ0h0WGVJaTFUaEIvanE1djJZClJLa3RzYXFNMnBSOTMwRGxpbDEx
            YzdxRGJDNFpQaGova0VZcG9zdHV0MUkKLS0tIG80R1U0NUJ0ZlZ4UGJhU2dLVEJ4
            N0JHamJsSlZzNHVFSnNZbTlmd0RjdmcKB765mHQ+sd19oRHVSEJyBlNWGnfEMahc
            w1RgTvejuSlQEFDCRZiRLfwJ+UrTwNOUlvPbIUA83S98rwKO139a4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T20:55:19Z"
    mac: ENC[AES256_GCM,data:uN0Xsq2W+rYmINEwA5qKYvLEKeqQooOqhKlzHonslVB7h4KHEzWUrzlssR95m+kEG4v0mWFa20ON4zLuQhpdh1jvMnkK5XJqvy+YNImpbo92JWv4Dkwq5c4e44dUcxmvOWXdF8uVyvvBTR6o+uiHOz3m3p3td+Di3pUTJh7ip9g=,iv:PRw8x1watnqW+xCc5fDOdlP/Hy/nX/SPXkxuk6b8CVc=,tag:puLB1S1pTpSQxuVMkPKglA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
