apiVersion: v1
kind: Secret
metadata:
    name: planka-secrets
    namespace: dev
stringData:
    OIDC_ISSUER: ENC[AES256_GCM,data:xWriDGK7gRbIR4amL27fFagcMoO5JMMfwXnN+nbegWdAYpY5RiO8jQLaew==,iv:GcZw6/nlYwC/yI9ofaUOouLXZ4cd//Sr7yJjt85Wle0=,tag:X88nmPpjhAKq5ORw2Hzueg==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:G2PDigVRtgDc9uOVFjMrGBFlz3hIkyRaN9iTLdm4ZGobCSzrjgWlcg==,iv:3wrxdWpDHh7Xvn4lkgmtLB7Saq18ttjq3IU/wUlutQg=,tag:4ryVJvsIlZPG7EzdgcCpoA==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:J/2EHp1HpEsFmWqOs8RysZ2Pp76RnpdRCRzl+83yNb2fJIBRzlQTmBGf7gpGf9ZWXxbLtSsaywICP0ZgcZghl3k3Eb9WTVymuzDjYnnid+LCGlVKdLG7PCmN3Hb+TkBwklALavxMyiCs3F+y9hwcnWH9k2qyOaqIjstoqEio7hk=,iv:+WHiA5cl4+kiMiJ9a8Ib+UNIotvlVmk3dwYQu+aGou0=,tag:jd5uHnw4BRxXyBf38cVoWQ==,type:str]
sops:
    age:
        - recipient: age1e8t93m32pkq6v5pgce4gm39xmtm967j9scmnvnrwpkaccwvunsyspwz3kp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBV1J2c3JOdU9mUUpmemI2
            UWRrY3FvZllCQ0h0WGVJaTFUaEIvanE1djJZClJLa3RzYXFNMnBSOTMwRGxpbDEx
            YzdxRGJDNFpQaGova0VZcG9zdHV0MUkKLS0tIG80R1U0NUJ0ZlZ4UGJhU2dLVEJ4
            N0JHamJsSlZzNHVFSnNZbTlmd0RjdmcKB765mHQ+sd19oRHVSEJyBlNWGnfEMahc
            w1RgTvejuSlQEFDCRZiRLfwJ+UrTwNOUlvPbIUA83S98rwKO139a4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-20T20:56:48Z"
    mac: ENC[AES256_GCM,data:QtkkcEF249q4LF3zV3Kk2xuC6fjFnjD3XWrrP8pre7KWPtmH8e887XMODdihwHCesFA4yIF3pLr+DeXlJz2zNcJ1ArM2y2TNtRNc2lzY003Xq2ulI4LuZ2zGDIDiBbbhspPBBgRldJ7Yywi62nt1m9UUEKjY3nf/9vIcQHaO2oo=,iv:2Lm3Js9HmhfPEVPXIHjdx0Q/3GX3hYhHw3JI4jW+PTQ=,tag:v/kytUpH0qgsfh5ABsBObQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
