apiVersion: v1
kind: Secret
metadata:
    name: planka-secret
    namespace: dev
stringData:
    REDIS_PASSWORD: ENC[AES256_GCM,data:3zessDZvtt6A2OrwWy22JTNx3EKCbedVYFa8iqtpWkSyF4Q6mkmRMXGseXhQZfAbWG1EzP9F31UNuqby2kY=,iv:fngqZoXPTHkjyOhjH4W68I9klsAqBmuQ5COEXkqDuqI=,tag:wJSYoXwKbJkhVyU/dV2F6A==,type:str]
    email-password: ENC[AES256_GCM,data:vmwO+rSO1v8ZiDlArtToPA==,iv:2Hq/R0z/cE1uAyaobrXHOyboa1CeOq867kcPVUiRJAQ=,tag:pLWdVlLViophfu4tOaDFPA==,type:str]
    username: ENC[AES256_GCM,data:zHD02FQ=,iv:k7KBCYd4zJ7K4ht01cIisO6RUfXO/IdYrBlrf22IdVk=,tag:89nq/XaQ0sO8u43/1y+oXg==,type:str]
    password: ENC[AES256_GCM,data:4cMQ8GHjs9esA+h+RA==,iv:MEXBCc2V86j7O3Fb3I9pn96gkJ3RZjrqWDVBTGb32gw=,tag:CB021tJWIOfB+qgkBzRKJA==,type:str]
    api_token: ENC[AES256_GCM,data:gRnQR+2HoT4GWQomseY1yb0Mr0bvCnV6GogSqPgpxxx7/VlwD+m2ntTgvNHxcwuMb6iUFR8D2RSu2JGiCIcn9Q==,iv:4ujAKhGxD8zglyJF6pbUNoFfiSd7p6c3V/zg3LQGYG8=,tag:q3jvEZqMM2gWr6mtffYCVw==,type:str]
    email: ENC[AES256_GCM,data:kTc+na1tTViFGhm5OC6r0v3CuNOOqX6KlMEoGXLNIh8=,iv:+3zM5iGAMLq+0UuFkrYkMHZHy9u/72yPd0jG2FxInN0=,tag:KbOZnKP957XG7bGon96ioA==,type:str]
    secret_key: ENC[AES256_GCM,data:38REZtrWE/oEVAaXgqmGb2rNNwbcPpofxke8bIK195ssAZrc5JWaGP77HQaTZzF9mN/h6TAmoeh3oKrZ8YD9fA==,iv:P1xGep8glBylgIks2B93GlziMV/LzKaBKyVppUMadJ4=,tag:s1EsJmwvu1knkiNOA6LoUw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8t93m32pkq6v5pgce4gm39xmtm967j9scmnvnrwpkaccwvunsyspwz3kp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVb2dDWm4raWc3MHYxVGRm
            dkhSbzVGMHF5OUhFSnVRVm9sWllaOWkvSWhnCi9OeTAxNGlyc0dDd2xmd3pySENL
            d2dPck0yelZ4VGx5Q1E1QWRBYk9rdHMKLS0tICtTVzJTSEQwQ2xSa0xSRDdsTTIw
            RjZkeEoxUmhwZGwvditNVzlvRUQ1VncKbNEf43ZE+UARbptUpniFvR8lgkgymOhr
            P4+KUx14x0d7Bh8AupvRsyXf58Wx9AX1W0c/nY2e7zPJi4LiFr7n/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-02T15:51:15Z"
    mac: ENC[AES256_GCM,data:qLgYWngPSapw9wVzx3FB7NuPhoc+tAqqbEzAqYSUyIKP3+AYB+RStiq+YwSYSpCXBTd7r8ljEzJPTXg+0uNrjkrubPGsRzsi2wuKPwCh3nOqUaLzc1w2TNXeABEOsApgNPTpl+pIRei3NWSvtwcIN5jJhgvFbUSfZONzDWrLuCA=,iv:jbG+AeTdQbXgARNvgbPvol/fdX2zCOZSMGG8K8oPq0s=,tag:POuxBVlzWKT+xqwXzDkQGg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
