apiVersion: v1
kind: Secret
metadata:
    name: homebox-secrets
    namespace: home
stringData:
    HBOX_OIDC_ISSUER_URL: ENC[AES256_GCM,data:PvEN3uA1VkHTt+WCkF+m6Umqfha1VoBM3guFMvtfX6LyjOw+OPhzomwMVlY=,iv:bI//A6KikR9+8c2qwPl6at6SDPKNo2FVA5DBT1us9rk=,tag:v27L92/f0lZ0qpDuPY6hiA==,type:str]
    HBOX_OIDC_CLIENT_ID: ENC[AES256_GCM,data:/7mWsnSEKQ0GewV0gIc4ZVauCK0qWxCkNg7KM4kBU8u2uIrd8o8OPw==,iv:YKgN44nrw8OYTsbSH24dUZBGn0Toq9LFJiSSmLFiK9w=,tag:xDzAUrRWxaeOL0Tml+YvrQ==,type:str]
    HBOX_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:7BqAnVZE2dNWe3DaJfqXxpWDKYUQ4i9L6s2Dhz3KHIqcBlJFJPGe6swdRdMrSeF2xgy+z+KIH3OJrDWODNEXwuNs6LbxhI3N+oJEgetFX8VBp/5PDl5B/UF1upm7RZf9Nusk7HwD+w1CDdSzf4yVDqQbAqjtMxxJ512cmurFf1o=,iv:v5htIwHYUMVHeA6kKNgOraiUNcG1WMuyIlnbPQjvbpM=,tag:3SC0zB0jsV7+g3tirIgjCA==,type:str]
    HBOX_OPTIONS_TRUST_PROXY: ENC[AES256_GCM,data:fbnBgg==,iv:G1yvr8j2Kgaraudy/1ipxnr4nRS4WQhK4RGduEFtCfU=,tag:SZuOkM24vTz8zJBSOzpBIQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8t93m32pkq6v5pgce4gm39xmtm967j9scmnvnrwpkaccwvunsyspwz3kp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBV1J2c3JOdU9mUUpmemI2
            UWRrY3FvZllCQ0h0WGVJaTFUaEIvanE1djJZClJLa3RzYXFNMnBSOTMwRGxpbDEx
            YzdxRGJDNFpQaGova0VZcG9zdHV0MUkKLS0tIG80R1U0NUJ0ZlZ4UGJhU2dLVEJ4
            N0JHamJsSlZzNHVFSnNZbTlmd0RjdmcKB765mHQ+sd19oRHVSEJyBlNWGnfEMahc
            w1RgTvejuSlQEFDCRZiRLfwJ+UrTwNOUlvPbIUA83S98rwKO139a4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T08:07:43Z"
    mac: ENC[AES256_GCM,data:nCquCk0uUEXw9pLmEtNk68XMkCxSg3wpttiNa3s73CIyVChcXUZA4jlhnspaxmL0VFhtMVeyRf7qxJgn/l628X65tUUX0gbZSGdMDr5qqULzOU3YCfcP9T5S/yxrPpTc1yIUR06a5sXqytrwcX9x/psgJGh/qVuHGhzabIwSZIU=,iv:7o2guxkME300qU9VLYP3aYOVMpaNV3ABzDmFLMyKFbI=,tag:Ba3xXs37Uh7L3CJpj+bsTw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
