---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
components:
  - ../../components/common
resources:
  - ./coder/ks.yaml
  - ./initiative/ks.yaml
  - ./ittools/ks.yaml
  - ./n8n/ks.yaml
  - ./netbox/ks.yaml
  #- ./planka/ks.yaml
  - ./semaphore/ks.yaml
