apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-secret
    namespace: security
stringData:
    LASTFM_USERNAME: ENC[AES256_GCM,data:Ylw9FYI=,iv:sIlXBfyELTNi+5WmzNcnH6Gj2YcZb6CJ/3xtcW1ajfk=,tag:AYvksebmTt6vSn0XdvU6mg==,type:str]
    LASTFM_API_KEY: ENC[AES256_GCM,data:LbyjB8+PBOizZkA+PaJnNsqH0axQ65StOavnckFb6Z8=,iv:NJnO1lUazpB4eDsgmahx8xLIxhVJIMWPvjaec0Y76ec=,tag:qBxwBWVhPxYW8wVn1eepJg==,type:str]
    LIDARR_API_KEY: ENC[AES256_GCM,data:keCQZLCNNBykvkJqdDUCSXSr2AwWuBVxQFKk7h19eUjFpVKH6XBYCId7,iv:c5PCkGvu193zX6/sa1zhp8VQ6wK9bHXQ//Vss69zpn4=,tag:Kx8KApuCkew+phQE2XcPog==,type:str]
    LIDARR_ENDPOINT: ENC[AES256_GCM,data:F6zB60x+6vtmeUzSIJJ6wkxcPm7DML80NmDzscFMqc6mbTKbcQ==,iv:stGIl41Rcif1APajCIEjGqKgrluY+esdRVuU28xwNJw=,tag:MXS+wWcg6g6dO/MjnHXW8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8t93m32pkq6v5pgce4gm39xmtm967j9scmnvnrwpkaccwvunsyspwz3kp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVb2dDWm4raWc3MHYxVGRm
            dkhSbzVGMHF5OUhFSnVRVm9sWllaOWkvSWhnCi9OeTAxNGlyc0dDd2xmd3pySENL
            d2dPck0yelZ4VGx5Q1E1QWRBYk9rdHMKLS0tICtTVzJTSEQwQ2xSa0xSRDdsTTIw
            RjZkeEoxUmhwZGwvditNVzlvRUQ1VncKbNEf43ZE+UARbptUpniFvR8lgkgymOhr
            P4+KUx14x0d7Bh8AupvRsyXf58Wx9AX1W0c/nY2e7zPJi4LiFr7n/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-19T11:50:21Z"
    mac: ENC[AES256_GCM,data:XG40Z3OoMSzF97bD6zp315dZh59fpxN16NTCfRbKoIexiHzGB0KfaO5tOr82mfEAPFeyuI23KunLA7sLqcLbS14o8DKnHuR8Mjuatza5IdNjgh38ndaz0F+IaLSRZr+dFxSQndHXjQpZXXL/mBvJ8OKZ+rYO/ks4qGOq5HWv0Xk=,iv:8RHcL8qfwxXvrs+3vTh56zni104WHW8tmpRILJ908Ws=,tag:9XFADKnp83F6rXAwhZ+x0A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
