apiVersion: v1
kind: Secret
metadata:
    name: initiative-secrets
    namespace: dev
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:f/kiPqb5Kj3cxkkRISrZG21noqMeL9wfWGET0jBfuDzZy/DrYuizR4IsKJbt/HTAXNF89IN9oCfg++iMmkTkaQ==,iv:lj2apYbOv9DmvD6AnBiN1nnZ0EZZpmOHRRMk+QZgUWE=,tag:y5143lJdphgOGaiZZt4ZQg==,type:str]
    OIDC_ISSUER: ENC[AES256_GCM,data:Fga/yiU5r00R/uIgEFjZlT3CX/TaLAOEVoFowgcTlvuq56eLYiSmU+sDrlv3HfDaXV5gYFaLQl0fATPJ41JB7u+BHLDfx1NKBoTlnOguxg==,iv:dfB4YfKBuuQxemn3RAxXcDvJMf2ry7U1t8MlDTYsl40=,tag:AsLiZeBJM1ZvqYGRggeR8g==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:JL/MGWJAGpAndJ53tB+jTMtVxIR82LyJSnlo619WhVCYr9qQaBxaAA==,iv:p9S6qEXVXyfZmWxg83tqRZm351AF3+IHHJJxZjGzA3o=,tag:uDqfGH6HOxCWpRqk7262lg==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:lv/bVHva5aiVbhR3Lk10Zw29oFB3SqXTK3bQGWGmfZcigXvs6OxewpbkyVwpxP3gIBFa+3pM293DSjCQqGvgz3MlofO5cFQXMW0638M4diQxPgG3kKaHsr2d1VCEBm/n/WFIQ5W1pnkjdiTXQdQhoqlUDIVgo/yuKEJ11t9Rx+Q=,iv:Y604YDdzGPfPx8Fb35DkyHha7pa72DQDb6+3D2j0eFI=,tag:R3NlBXBQ81LZoq0IwYtDsQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8t93m32pkq6v5pgce4gm39xmtm967j9scmnvnrwpkaccwvunsyspwz3kp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBV1J2c3JOdU9mUUpmemI2
            UWRrY3FvZllCQ0h0WGVJaTFUaEIvanE1djJZClJLa3RzYXFNMnBSOTMwRGxpbDEx
            YzdxRGJDNFpQaGova0VZcG9zdHV0MUkKLS0tIG80R1U0NUJ0ZlZ4UGJhU2dLVEJ4
            N0JHamJsSlZzNHVFSnNZbTlmd0RjdmcKB765mHQ+sd19oRHVSEJyBlNWGnfEMahc
            w1RgTvejuSlQEFDCRZiRLfwJ+UrTwNOUlvPbIUA83S98rwKO139a4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T01:11:32Z"
    mac: ENC[AES256_GCM,data:3IdZlCB6aVqfIY9LBzZwFF/a/3xdveNhBXzkvA2omUIj/tkICG2jvgLSpGiau+aS2WI3NbVCpqdrjt9i35QselHosu0NVt026+CEQg0LGEE8rTnb3KkDYyx4fXLTIShgujLtKXfWkmBWiFpBR0pu5WDt1+auPm61/hJ6SDX2/VM=,iv:8yHw4AXgA6VdhmAkfQ6AyW+2798A+GKyRXVOrMnc1w0=,tag:FCyk+bpbPQzdypudrQxNLg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
