apiVersion: v1
kind: Secret
metadata:
    name: initiative-secrets
    namespace: dev
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:f/kiPqb5Kj3cxkkRISrZG21noqMeL9wfWGET0jBfuDzZy/DrYuizR4IsKJbt/HTAXNF89IN9oCfg++iMmkTkaQ==,iv:lj2apYbOv9DmvD6AnBiN1nnZ0EZZpmOHRRMk+QZgUWE=,tag:y5143lJdphgOGaiZZt4ZQg==,type:str]
    OIDC_ISSUER: ENC[AES256_GCM,data:Fga/yiU5r00R/uIgEFjZlT3CX/TaLAOEVoFowgcTlvuq56eLYiSmU+sDrlv3HfDaXV5gYFaLQl0fATPJ41JB7u+BHLDfx1NKBoTlnOguxg==,iv:dfB4YfKBuuQxemn3RAxXcDvJMf2ry7U1t8MlDTYsl40=,tag:AsLiZeBJM1ZvqYGRggeR8g==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:JL/MGWJAGpAndJ53tB+jTMtVxIR82LyJSnlo619WhVCYr9qQaBxaAA==,iv:p9S6qEXVXyfZmWxg83tqRZm351AF3+IHHJJxZjGzA3o=,tag:uDqfGH6HOxCWpRqk7262lg==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:lv/bVHva5aiVbhR3Lk10Zw29oFB3SqXTK3bQGWGmfZcigXvs6OxewpbkyVwpxP3gIBFa+3pM293DSjCQqGvgz3MlofO5cFQXMW0638M4diQxPgG3kKaHsr2d1VCEBm/n/WFIQ5W1pnkjdiTXQdQhoqlUDIVgo/yuKEJ11t9Rx+Q=,iv:Y604YDdzGPfPx8Fb35DkyHha7pa72DQDb6+3D2j0eFI=,tag:R3NlBXBQ81LZoq0IwYtDsQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:Q3mCuFa8qPOZZaWSe883KWosm/UH7WIxpwd/m5kXonBwVKjQs84nTl7qCDjjawOrVDrxeuL8tmpEUPXxYCtwxr8Jgg9tdeerEiC2wCSmcs7EK/RRW8z0xUarf3xxTZliCFjlWPBXKgo=,iv:80SLI2k68Z3WqSfw29RuQvBkEhL1z4R3WUxrkPYcIsA=,tag:SaEMwO7nJPAcCXsfohwtfQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8t93m32pkq6v5pgce4gm39xmtm967j9scmnvnrwpkaccwvunsyspwz3kp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBV1J2c3JOdU9mUUpmemI2
            UWRrY3FvZllCQ0h0WGVJaTFUaEIvanE1djJZClJLa3RzYXFNMnBSOTMwRGxpbDEx
            YzdxRGJDNFpQaGova0VZcG9zdHV0MUkKLS0tIG80R1U0NUJ0ZlZ4UGJhU2dLVEJ4
            N0JHamJsSlZzNHVFSnNZbTlmd0RjdmcKB765mHQ+sd19oRHVSEJyBlNWGnfEMahc
            w1RgTvejuSlQEFDCRZiRLfwJ+UrTwNOUlvPbIUA83S98rwKO139a4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T01:31:09Z"
    mac: ENC[AES256_GCM,data:CciZziJYFyDXdlKsxYYFuD6H+DMRAwxdstKXLZPgrAWT2Obul6GOMjTI0wphtKIXvgdmfezDHw8zSAz7JF5Xk8x4kQ+OkyWNZluQdJbU1myeLcGRDFyg08+4A7rwSwcRxHnZ8V2lYqeMjLZh7zQC0X7cVsTcVTXqHIU+W3dCn5U=,iv:24W9zvISid8L1URZ7yF0xLER+ZyMtUxbWvHelXmYYkc=,tag:w8G6CifSDBr2ir7GWi8ZLw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
