---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pocket-id-pv
spec:
  storageClassName: csi-cephfs-sc
  claimRef:
    name: pocket-id
    namespace: security
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: cephfs.csi.ceph.com
    nodeStageSecretRef:
      # node stage secret name
      name: csi-cephfs-secret
      # node stage secret namespace where above secret is created
      namespace: storage
    volumeAttributes:
      # Required options from storageclass parameters need to be added in volumeAttributes
      "clusterID": "ace7b6a4-115a-42f7-ba4f-32ceeb11e3c3"
      "fsName": "k8s-cephfs"
      "staticVolume": "true"
      "rootPath": /volumes/csi/k8s-security/pocket-id
    # volumeHandle can be anything, need not to be same
    # as PV name or volume name. keeping same for brevity
    volumeHandle: pocketid




---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pocket-id
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-cephfs-sc
  volumeName: pocket-id-pv
