apiVersion: v1
kind: Secret
metadata:
    name: pocket-id-secret
    namespace: ${NS}
stringData:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:kT67UhGqiGJWtoRHITUZVtPZthu3bxLEDfNgq5Frju+h20YNEHxrkVcXnj0IzWP7YZZmZcfoLYqGklEtOrC9Tg==,iv:i+MgXxw0I1GuLeB+KwD+QvvcpB8mMK6oY66O5a3ogy0=,tag:ngu1aOFW3oHB9gWAIMtk8Q==,type:str]
sops:
    age:
        - recipient: age1e8t93m32pkq6v5pgce4gm39xmtm967j9scmnvnrwpkaccwvunsyspwz3kp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBV1J2c3JOdU9mUUpmemI2
            UWRrY3FvZllCQ0h0WGVJaTFUaEIvanE1djJZClJLa3RzYXFNMnBSOTMwRGxpbDEx
            YzdxRGJDNFpQaGova0VZcG9zdHV0MUkKLS0tIG80R1U0NUJ0ZlZ4UGJhU2dLVEJ4
            N0JHamJsSlZzNHVFSnNZbTlmd0RjdmcKB765mHQ+sd19oRHVSEJyBlNWGnfEMahc
            w1RgTvejuSlQEFDCRZiRLfwJ+UrTwNOUlvPbIUA83S98rwKO139a4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-12T08:24:59Z"
    mac: ENC[AES256_GCM,data:D77oZlLtKuxBn8eY1vl3antS4AAKHVWV3LZYZPJCLO2kTJCTTxJ9jAyfjnIiy85PUHE4ASuwkj1Cetqx4tgI3hvyny2NWpMc15F8W+KXyceBfoNH5V22GhT/8Y6re7mM3AJbFCSuLNKXCYeLlFlHkGef93OeqQYJ/j8IzN6KQBE=,iv:c+yubaX56u0X5t+vqnQLIXGtcq8mSdlY7rCgyuTyc98=,tag:kgNBICpk4DVBeDdhzl4iLA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
